apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ include "ms-general.name" . }}
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app:  {{ include "ms-general.name" . }}
        tier: backend
        track: stable
    spec:
      containers:
        - name: ms-general
          image: "{{ .Values.DockerRepo }}:{{ .Values.DockerTag }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
---   
