apiVersion: v1
kind: Service
metadata:
  name: {{ include "ms-general.name" . }}
spec:
  selector:
    app: {{ include "ms-general.name" . }}
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30091
  type: NodePort
---
 
